services:
  - type: web
    name: ipl-dashboard
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SERVER_PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true